apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: tasks
data:
  MYSQL_HOST: "mysql-service"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "taskdb"
  MYSQL_USER: "root"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  API_URL: "http://backend-service:3000"
