apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: tasks
  annotations:
    "helm.sh/resource-policy": keep
spec:
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: wait-for-mysql
        image: busybox
        command: ['sh', '-c', 'until nc -z mysql-service 3306; do echo waiting for mysql; sleep 2; done']
      containers:
      - name: migrate
        image: {{ .Values.image.registry }}/task-api:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["node", "migrate.js"]
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mysql-password
  backoffLimit: 3
