apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: tasks
type: Opaque
stringData:
  mysql-password: {{ .Values.secrets.mysqlPassword | quote }}
  redis-password: {{ .Values.secrets.redisPassword | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
