apiVersion: v1
kind: ConfigMap
metadata:
  name: url-shortener-config
  namespace: {{ .Release.Namespace }}
data:
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
