apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-frontend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app: url-frontend
  template:
    metadata:
      labels:
        app: url-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.registry }}/{{ .Values.image.frontendRepository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: url-frontend-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: url-frontend
  ports:
    - port: 80
      targetPort: 80
